default_platform(:ios)

platform :ios do
  desc "Builds, achieves and uploads ipa to TestFlight"
  lane :testflight_lane do
    # add actions here: https://docs.fastlane.tools/actions
      cert
      sigh
      increment_build_number
      gym(
       scheme: "Nouter",
       export_method: "app-store",
       export_xcargs: "-allowProvisioningUpdates"
          )
      upload_to_testflight(
           skip_submission: true,
           skip_waiting_for_build_processing: true
      )
  end
end
